# Generated by Django 5.1.2 on 2024-10-13 14:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item2plant_model',
            fields=[
                ('relate_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_id', models.IntegerField()),
                ('plant_id', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'item2plant',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='item_model',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_status', models.CharField(choices=[('active', 'active'), ('deleted', 'deleted')], default='active', max_length=20)),
                ('item_name', models.CharField(max_length=200)),
                ('img_link', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('short_description', models.CharField(max_length=255)),
                ('long_description', models.CharField(max_length=1000)),
                ('specification', models.CharField(max_length=400)),
                ('item_cost', models.IntegerField()),
                ('item_type', models.CharField(choices=[('solar_panel', 'solar_panel'), ('battery', 'battery')], max_length=20)),
                ('item_voltage', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_capacity', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('item_power', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='plant_model',
            fields=[
                ('plant_id', models.AutoField(primary_key=True, serialize=False)),
                ('plant_status', models.CharField(choices=[('draft', 'draft'), ('deleted', 'deleted'), ('completed', 'completed'), ('formed', 'formed'), ('rejected', 'rejected')], default='draft', max_length=20)),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('forming_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('finishing_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('creator_login', models.CharField(max_length=50)),
                ('moderator_login', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('generation', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('saving', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=5, default=None, max_digits=8, null=True)),
                ('fio', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plants',
                'managed': False,
            },
        ),
    ]
