# Generated by Django 5.1.3 on 2024-11-07 16:56

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0003_alter_plant_model_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 16, 56, 1, 763499)),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creator',
            field=models.ForeignKey(db_column='creator', default='1', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
