# Generated by Django 5.1.3 on 2024-11-07 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0004_alter_plant_model_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 16, 57, 55, 265280)),
        ),
    ]
