# Generated by Django 5.1.3 on 2024-11-07 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0005_alter_plant_model_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 17, 8, 25, 908252)),
        ),
    ]
