# Generated by Django 5.1.3 on 2024-11-07 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SolarPlants', '0006_alter_plant_model_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='plant_model',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 17, 13, 0, 853027)),
        ),
    ]
