# Generated by Django 5.1.2 on 2024-11-06 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SolarEnergy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item2plant_model',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='item_model',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='plant_model',
            options={'managed': True},
        ),
    ]
